### PR TITLE
accessibility localization tweaks

### PR DESCRIPTION
**Pull request by abaevbog**
- Removed "Item 1" prefix if only one item is being saved. The new announcements will be just "Saving item {title}. Saved snapshot for this item"
- "Web link" instead of "Linked attachment" as the item type label
- Added epub content type to be announced as an attachment
- Use `general_saveTo` string for the label of the dialog
- Added aria-labels to the expand/collapse twisty button (vpat 39). I started with "View details"/"Hide details". Correct me if there's a more descriptive way than "details" to refer to the collections table and the tags area together.
- Added aria-label to the collection selector table so that it indicates what that element if for when a row is focused. Again, let me know if there is a better way to name this than "Target collection selector".
- Fixed a race condition bug to not trigger handle alerts until all top level items are 100 percent loaded.

Fixes: #472

### CODE REVIEW

**Comment by dstillman** [comment]
I haven't tested without this PR, so probably not from this specifically, but can we do anything about the backwards order here (collection before "Saving to")? Maybe it's correct, in the weird logic of screen readers, because it's telling you the current value before giving you the context?

Screenshot 2024-05-16 at 7 18 13 AM

Can we do anything to announce the dialog closing? I'm finding it keeping the VO selection in place even after the dialog closes, with no announcement that that happened.

**Comment by abaevbog** [comment]
> I haven't tested without this PR, so probably not from this specifically, but can we do anything about the backwards order here (collection before "Saving to")? Maybe it's correct, in the weird logic of screen readers, because it's telling you the current value before giving you the context?

The exact way of how the elements' announcements are put together based on the DOM and aria properties is something that's specific for each screen reader. Voiceover is particularly odd about it - it always says value first and label after. On the contrary, JAWS and NVDA both say "Saving to combobox '{Selected collection}'" for that dropdown. So I don't think this is something we can or should try to change, since this way of announcing things seems specific to voiceover and users are likely accustomed to and expect it...

Somewhat related to this is that voiceover often decides to immediately announce the focused menupopup and skip the explicit "Saving to {collection}" [alert](https://github.com/zotero/zotero-connectors/blob/aa198b4a29d2335cebc9de59f95fd6e2a9189513/src/common/ui/ProgressWindow.jsx#L202) that fires right as soon as the popup opens. This would have helped to clarify things a bit. In general, I've noticed that voiceover may unfortunately skip some `aria-live` announcements depending on what else is going on.


> Can we do anything to announce the dialog closing? I'm finding it keeping the VO selection in place even after the dialog closes, with no announcement that that happened.

That is a great point! I added a new `progressWindowIframe.willHide` message that fires when all saving is done, so it will add an additional message before the dialog closes. Let me know if the phrasing should be tweaked. I went with "Saving is complete. The dialog will close now." as a start.

Also, I added a special alert that the items have already been saved on re-opening of the dialog. That way, it doesn't say "Saving to ..." because then it does make it seem like it's saving duplicate items, which is not true.

[New announcements video](https://www.dropbox.com/scl/fi/h3nvmum0cnq3kz0bwbu79/new_announcements.mov?rlkey=8x9ttoszlk8sg42ppd3rj9721&st=13e9tm3t&dl=0)

**Comment by abaevbog** [comment]
A somewhat bigger issue I noticed with voiceover is that it does not announce anything at all if the focus/cursor is not in the actual web page. That means that if you tab into the "Save to zotero" extension button in browser's toolbar and press "Enter", nothing gets announced because (I think) the focus is on the toolbar. Since NVDA and JAWS do not have this issue, it seems like just another oddity of voiceover that I'll try to workaround somehow

**Comment by adomasven** [comment]
Merging as this is an improvement over the current state and we want to release it and we can refine further if need be.

**Pull request merged**
